# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

# config/services.yaml

services:

    admin.event:
        class: App\Admin\EventAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Event, manager_type: orm, label: Event }
    admin.ticket:
        class: App\Admin\TicketAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Ticket, manager_type: orm, label: Ticket }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
